### ISSUE TITLE
GDM theme installation causing GNOME font to become fullwidth

### ISSUE THREAD

**Issue by haoyet** [vinceliuice/Mojave-gtk-theme#33]
If I install the GDM theme then I would get wider fonts in GNOME, but it was find in Budgie.

![image](https://user-images.githubusercontent.com/28365438/57189375-1d015d80-6edc-11e9-9b1b-3fa435f7589b.png)

However, this only happens to GNOME panels and does not affect the applications

![image](https://user-images.githubusercontent.com/28365438/57189385-34d8e180-6edc-11e9-9a77-242ce6e38b25.png)

**Comment by vinceliuice** [comment]
Sorry, I don't know why the shell theme can affect the font settings, anyway you can run ./install.sh -r to remove the gdm theme

**Comment by haoyet** [comment]
> Sorry, I don't know why the shell theme can affect the font settings, anyway you can run ./install.sh -r to remove the gdm theme

More exactly, it is the gnome-shell theme causing this problem

**Comment by vinceliuice** [comment]
I get it now, If you are not using ubuntu then this will happen, because system will use GDM theme  as a supplement to the current theme, which will show some features that are not available of the user theme, that will lead to some confusing display effects. If you want to use other gnome-shell themes, you are advised to delete this GDM theme.
