### ISSUE TITLE
Firefox CSS dark theme not working

### ISSUE THREAD

**Issue by atticushm** [vinceliuice/Mojave-gtk-theme#55]
Hi there,

Congrats on this awesome theme, it looks incredible and fits perfectly with the macos gnome GTK theme.
However, I can't seem to get the dark theme working. The light theme works great, but when I go to select the dark theme in the Firefox Customization menu, the Firefox top ribbon (search bar, buttons, everything) remains in the light theme.

Any ideas? Thankful for any help!

**Comment by atticushm** [comment]
Just realised my error - I need to edit the userChrome.css file.

**Comment by bruno-anjos** [comment]
Did you fix this? Because i just cloned and i still get this issue

**Comment by vinceliuice** [comment]
@bruno-anjos Please read this
https://github.com/vinceliuice/Mojave-gtk-theme/blob/master/src/firefox/README.md

**Comment by bruno-anjos** [comment]
Hey i ended up figuring how to fix it, maybe you could specify a bit more here

https://github.com/vinceliuice/Mojave-gtk-theme/blame/master/src/firefox/README.md#L24-L27

that if you want to change to dark theme, you have to change in the userChrome.css, because you only mention changing in the firefox customization panel
